"""empty message

Revision ID: d16f311e38c6
Revises: 
Create Date: 2017-06-07 22:49:29.832962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd16f311e38c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'path_to_img')
    op.drop_column('artists', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('description', mysql.VARCHAR(length=5000), nullable=True))
    op.add_column('artists', sa.Column('path_to_img', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
